---
- hosts: dev
  become: True
  tasks:   
    - name: Install docker-ce (centos) via amazon-linux-extras packages
      shell: "amazon-linux-extras install docker=18.06.1 -y" 
    - name: Package Installer For Python3 
      package:
        name: python-pip
        state: present
    - name: Installing python library for the Docker Remote API
      pip:
        name: docker-py
    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes
    - name: Start the container
      docker_container:
        name: nodejsapp
        image: "mcoria/nodejsapp:{{DOCKER_TAG}}"
        state: started     
        published_ports: 8080:8080
        state: started

      