---
- hosts: dev
  become: True
  tasks:    
    - name: Install Docker
      yum:
        name: docker
        state: started
        enabled: yes  
    - name: Start the container
      docker_container:
        name: nodejsapp
        image: "mcoria/nodejsapp:{{DOCKER_TAG}}"
        state: started     
        published_porst:
          - 0.0.0.0:8080:8080
      